{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ubuntu.serviceAccountName" . }}
  labels:
{{ include "ubuntu.labels" . | indent 4 }}
{{- end -}}
