apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: 
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ubuntu
        version: v1
    spec:
      containers:
      - name: ubuntu
        image: docker.io/library/ubuntu:latest
        command: [ "sh", "-c", "while true; do echo $(hostname) v1 > /data/index.html; sleep 60; done" ]
        volumeMounts:
        - name: content
          mountPath: /data
      volumes:
      - name: content
