{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "centos.serviceAccountName" . }}
  labels:
{{ include "centos.labels" . | indent 4 }}
{{- end -}}
