{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "stratos.serviceAccountName" . }}
  labels:
{{ include "stratos.labels" . | indent 4 }}
{{- end -}}
